### ISSUE TITLE
Is there a way to use Django Cabinet with CKEditor?

### ISSUE THREAD

**Issue by GasimGasimzada** [matthiask/django-cabinet#5]
I am trying to figure it out and maybe write views to achieve the result but I would like to know if this package has a native implementation for CKEditor image embeddings.

**Comment by matthiask** [comment]
No, there isn't yet such a thing. I'd be happy to add hooks if you need them, or additional attributes to the changelist, but I don't like image pickers too much in rich text editors (long version: https://feincms-django-cms.readthedocs.io/en/latest/advanced/designdecisions.html#about-rich-text-editors and https://feincms3.readthedocs.io/en/latest/ref/cleansing.html )

**Comment by matthiask** [comment]
So I worked on this a bit because we have a project where such an integration is desired (not by me!)

You'll have to include the `cabinet_ckeditor.admin.CKEditorFilebrowserMixin` mixin in your own `ModelAdmin` subclass for files (if you're not using a custom file model, try unregistering the admin class and re-registering it with your own version).

Next, add the `filebrowserBrowseUrl` to your CKEditor configuration with the following value: `{% url "admin:cabinet_file_changelist" %}?_popup=1&_to_field=id`

Uploading files from the file picker does not work, but browsing and selecting files does.
